# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0006_auto_20170416_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('yourName', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('requestSubject', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.TextField()),
                ('modifiedByfullName', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.BooleanField(default=False)),
                ('IsHidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.TextField()),
                ('modifiedByfullName', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topnavigations',
            name='RoleId',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='TopNavigations',
        ),
    ]
