# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0007_auto_20170419_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
    ]
