# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0008_auto_20170420_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='GoalsAwayTeam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='GoalsHomeTeam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
