# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DivisionName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Status', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('GoalsHomeTeam', models.IntegerField()),
                ('GoalsAwayTeam', models.IntegerField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('SeasonName', models.TextField()),
                ('Active', models.BooleanField(default=False)),
                ('IsHidden', models.BooleanField(default=False)),
                ('SeasonStart', models.DateTimeField(auto_now_add=True)),
                ('SeasonEnd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TeamName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('DivisionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions')),
                ('SeasonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('VenueName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='AwayTeamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='DivisionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='HomeTeamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='H', to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='SeasonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='VenueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Venues'),
        ),
    ]
