# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('yourName', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('requestSubject', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.TextField()),
                ('modifiedByfullName', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DivisionName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.TextField()),
                ('modifiedByfullName', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('GoalsHomeTeam', models.IntegerField(blank=True, null=True)),
                ('GoalsAwayTeam', models.IntegerField(blank=True, null=True)),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SeasonName', models.TextField()),
                ('Active', models.BooleanField(default=False)),
                ('IsHidden', models.BooleanField(default=False)),
                ('SeasonStart', models.DateField(blank=True, null=True)),
                ('SeasonEnd', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('DivisionId', models.ForeignKey(db_column='DivisionId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions')),
                ('SeasonId', models.ForeignKey(db_column='SeasonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('VenueName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='AwayTeamId',
            field=models.ForeignKey(db_column='AwayTeamId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwayTeam', to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='DivisionId',
            field=models.ForeignKey(db_column='DivisionId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='HomeTeamId',
            field=models.ForeignKey(db_column='HomeTeamId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeTeam', to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='SeasonId',
            field=models.ForeignKey(db_column='SeasonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='VenueId',
            field=models.ForeignKey(db_column='VenueId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Venues'),
        ),
        migrations.AddField(
            model_name='players',
            name='TeamId',
            field=models.ForeignKey(db_column='TeamId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Teams'),
        ),
    ]
