# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='modifiedBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='modifiedByfullName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
